source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CustomCollectionViews_Example', :exclusive => true do
  pod "CustomCollectionViews", :path => "../"
end

target 'CustomCollectionViews_Tests', :exclusive => true do
  pod "CustomCollectionViews", :path => "../"

  
end
